MainApp/urls.py
from django.urls import path

from . import views

app_name = 'MainApp'

urlpatterns = [
    path('',views.index,name='index'),
    path('pizzas',views.pizzas,name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),
    path('comment/<int:pizza_id>/',views.comment,name='comment'),
]

pizzeria_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainApp/models.py
from django.db import models

# Create your models here.
# super user pass: Snoopy#Callie23
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.topping_name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField(max_length=200)

    def __str__(self):
        return self.text

class Image(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')

    

MainApp/forms.py
from django import forms
from .models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text':''}

        widgets = {'text': forms.Textarea(attrs={'cols':80})}

MainApp/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *


# Create your views here.
def index(request):
    return render(request, 'MainApp/index.html')

def pizzas(request):
    pizzas = Pizza.objects.order_by('pizza_name')

    context = {'allpizzas':pizzas}
    return render(request, 'MainApp/pizzas.html', context)

def pizza(request, pizza_id):
    p = Pizza.objects.get(id=pizza_id)
    toppings = Topping.objects.filter(pizza=p)
    addcomment = Comment.objects.filter(pizza=pizza_id)
    image = Image.objects.filter(pizza=pizza_id)

    context = {'pizza':p, 'toppings':toppings, 'addcomment':addcomment, 'image':image}
    return render(request, 'MainApp/pizza.html', context)

def comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.pizza = pizza
            comment.save()
            
            return redirect('MainApp:pizza',pizza_id=pizza_id)

    context = {'form':form,'pizza':pizza}
    return render(request, 'MainApp/comment.html', context)

MainApp/templates/MainApp/base.html
<p>
    <a href="{% url 'MainApp:index' %}">Home</a>
    <a href="{% url 'MainApp:pizzas' %}">Pizza Pies</a>
</p>

{% block content %}

{% endblock content %}

MainApp/templates/MainApp/comment.html
{% extends "MainApp/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'newpformat.css' %}">
<p><a href= "{% url 'MainApp:pizza' pizza.id %}">{{pizza}}</a></p>

<p>Add a comment:</p>

<form action= "{% url 'MainApp:comment' pizza.id %}" method="post">
    {% csrf_token %}

    {{form.as_p}}

    <button name="submit">Submit</button>
</form>

{% endblock content %}

MainApp/templates/MainApp/index.html
{% extends "MainApp/base.html" %}

{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static 'format.css' %}">

<h1><p>CSU Pizza</p></h1>

<p> Char is the name, pizza is the game. For years, we have been providing our local community with a means to be merry with one another. Come by for a delicious pizza pie today!</p>

<img src="{% static 'IMG_3910x.JPG' %}" style="max-height:450px">

{% endblock content %}

MainApp/templates/MainApp/pizza.html
{% extends "MainApp/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'newpformat.css' %}">
<p>Pizza: {{ pizza }} </p>
<form method="POST">
    <ul>
        {% for t in toppings %}

        <p>-- {{ t.topping_name}} </p>

        {% endfor %}
    <br>
    </ul>
    <ul>
        {% for i in image %}
        <div class="col-md-4">
            <img src="{{ i.image.url }}" class="img-responsive" style="width: 30%; margin-right: 5px;" />
        </div>
        {% empty %}
        <p>No picture is given for {{pizza}}.</p>
        {% endfor %}
    </ul>
    
    <br><br> 
    <p style= "font-size:20px">Comments For {{pizza}} Pizza:</p>
    <br>   
    <ul>
        {% for c in addcomment %}
        <p>-- {{ c.text }} </p>

        {% empty %}
        <p> There are no comments for this pizza.</p>
        {% endfor %}
        
    </ul>

    <p><a href="{% url 'MainApp:comment' pizza.id %}">Add comment</a></p>
</form>
{% endblock content %}

MainApp/templates/MainApp/pizzas.html
{% extends "MainApp/base.html" %}

{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static 'newpformat.css' %}">

<p>Pizza Pies</p>

<ul>
    {% for p in allpizzas %}

    <li>
        <a href="{% url 'MainApp:pizza' p.id %}"> {{ p }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock content %}